### ISSUE TITLE
[1.16.3] Crash in dev environment on runData

### ISSUE THREAD

**Issue by UnPure** [FTBTeam/FTB-Library#3]
I'm using FTB-GUI-Library in my dev environment and everything is working fine if I start the client, but if I try to use runData I'm getting a crash from FTB-GUI-Library. 

**Crash:** https://pastebin.com/X7DYiQW0

**MC:** 1.16.3
**Forge:** 34.1.11
**FTB-GUI-Library:** 1.0.0.18

```
repositories {
    maven {
        name 'FTB GUI'
        url 'https://maven.latmod.com/'
    }
}
 
dependencies {
    minecraft "net.minecraftforge:forge:1.16.3-34.1.11"
    compile fg.deobf("com.feed_the_beast.mods:ftb-gui-library:1.0.0.18")
}
```

If you need to know any other informations, please let me know.

**Comment by WilliamBlaze** [comment]
The same Trigger causes a similar crash when using the ftb-gui-library-1605.2.1.40-forge.jar on the 1.16.5-forge-36.0.45 version of forge.

So I'm just going to copy the crash log below incase it might help solve the issue for both version(s):

Time: 3/9/21 1:01 AM
Description: mouseClicked event handler

java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy100.act(Unknown Source) ~[?:?] {}
	at com.feed_the_beast.mods.ftbguilibrary.utils.ClientUtils.handleClick(ClientUtils.java:243) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.handleClick(GuiBase.java:450) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Widget.handleClick(Widget.java:224) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.sidebar.SidebarButton.onClicked(SidebarButton.java:184) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.sidebar.GuiButtonSidebarGroup.func_230930_b_(GuiButtonSidebarGroup.java:175) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_231044_a_(CreativeScreen.java:436) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13699/1727151641.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13698/2068397857.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$11308/1729683601.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99) ~[?:mc1.16.4-1.18] {re:classloading}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:388) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.45.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/1625539182.call(Unknown Source) [forge-1.16.5-36.0.45.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at me.shedaniel.architectury.event.EventFactory$5.handleInvocation(EventFactory.java:163) ~[?:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84) ~[guava-21.0.jar:?] {}
	... 41 more
Caused by: java.lang.NoSuchMethodError: dev.latvian.mods.itemfilters.api.ItemFiltersAPI.getDisplayItemStacks(Lnet/minecraft/item/ItemStack;Ljava/util/List;)V
	at com.feed_the_beast.ftbquests.quest.task.ItemTask.getValidDisplayItems(ItemTask.java:136) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.task.ItemTask.getAltIcon(ItemTask.java:158) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.Quest.getAltIcon(Quest.java:509) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.Chapter.getAltIcon(Chapter.java:273) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:297) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.gui.quests.ButtonChapter.<init>(ButtonChapter.java:24) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.gui.quests.PanelChapters.addWidgets(PanelChapters.java:44) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Panel.refreshWidgets(Panel.java:71) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Panel.refreshWidgets(Panel.java:84) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.initGui(GuiBase.java:91) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiWrapper.func_231160_c_(GuiWrapper.java:31) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.func_231158_b_(Screen.java:325) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.openGui(GuiBase.java:392) ~[?:?] {re:classloading}
	at com.feed_the_beast.ftbquests.client.ClientQuestFile.openQuestGui(ClientQuestFile.java:136) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.client.FTBQuestsClientEventHandler.onCustomClick(FTBQuestsClientEventHandler.java:106) ~[?:1605.2.0-build.32] {re:classloading}
	at com.feed_the_beast.ftbquests.client.FTBQuestsClientEventHandler$$Lambda$5555/445010343.act(Unknown Source) ~[?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at me.shedaniel.architectury.event.EventFactory$5.handleInvocation(EventFactory.java:163) ~[?:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84) ~[guava-21.0.jar:?] {}
	... 41 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sun.proxy.$Proxy100.act(Unknown Source) ~[?:?] {}
	at com.feed_the_beast.mods.ftbguilibrary.utils.ClientUtils.handleClick(ClientUtils.java:243) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.GuiBase.handleClick(GuiBase.java:450) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.widget.Widget.handleClick(Widget.java:224) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.sidebar.SidebarButton.onClicked(SidebarButton.java:184) ~[?:?] {re:classloading}
	at com.feed_the_beast.mods.ftbguilibrary.sidebar.GuiButtonSidebarGroup.func_230930_b_(GuiButtonSidebarGroup.java:175) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_231044_a_(CreativeScreen.java:436) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13699/1727151641.run(Unknown Source) ~[?:?] {}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$13698/2068397857.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$11308/1729683601.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:99) ~[?:mc1.16.4-1.18] {re:classloading}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['WilliamBlaze'/3086, l='ClientLevel', x=-379.82, y=80.00, z=147.04]]
	Chunk stats: Client Chunk Cache: 529, 338
	Level dimension: minecraft:overworld
	Level spawn location: World: (-320,65,144), Chunk: (at 0,4,0 in -20,9; contains blocks -320,0,144 to -305,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3437 game time, 3437 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.45.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/1625539182.call(Unknown Source) [forge-1.16.5-36.0.45.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

**Comment by MaxNeedsSnacks** [comment]
I can't fully remember, did we fix this in newer releases?

Could you maybe test using a datagen again with newer versions of FTB Lib and see whether this issue persists?
